name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
env:
  HUSKY: 0
  ZX_VERBOSE: true
  DO_NOT_TRACK: 1
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  GOOGLE_SEARCH_TERM: ${{variables.GOOGLE_SEARCH_TERM}}
  SEARCH_TERM: ${{variables.SEARCH_TERM}}
  LOCATION: ${{variables.LOCATION}}
  NOCODB_CAREERS_BASE: ${{variables.NOCODB_CAREERS_BASE}}
  NOCODB_COMPANY_TABLE: ${{variables.NOCODB_COMPANY_TABLE}}
  NOCODB_JOB_TABLE: ${{variables.NOCODB_JOB_TABLE}}
  NOCODB_TOKEN: ${{secrets.NOCODB_TOKEN}}
  NOCODB_URL: ${{variables.NOCODB_URL}}
permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write
concurrency: ${{github.workflow}}-${{github.ref}}
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"
      - name: üêç "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: ü¶Ä Install uv
        uses: astral-sh/setup-uv@v7
      - name: üì¶ Installing dependencies
        run: pnpm install
      - name: üß∞ Download schemas
        run: pnpm build:schema
      - name: üõ†Ô∏è Generate rendercv
        run: pnpm build:cv
      - name: ‚ÜóÔ∏è Create release
        run: pnpm run release
      - name: ‚ÜóÔ∏è Update README
        run: pnpm run build:readme
